## Function makeCacheMatrix generates a list of functions that can be used to both set and retrieve a matrix and matrix inverse.
## Function CacheSolve calculates the inverse of a given matrix, or retrieve it from memory (if it already exists) 

## This function takes an argument x (a matrix) and generates a list of functions that can are used by cacheSolve

makeCacheMatrix <- function(x = matrix()) {
    
    inv <- NULL
    set.mat <- function(y){
        x <<- y
        m <<- NULL
    }
    
    get.mat <- function(){
        x
    }
    
    set.inv <- function(inverse){
        inv <<- inverse
    }
    
    get.inv <- function(){
        inv
    }
    
    list(set.mat = set.mat, get.mat = get.mat, set.inv = set.inv, get.inv = get.inv)

}


## This function uses the functions generated by makeCacheMatrix to either calcuate the inverse of a given matrix, or 
## return it from memory (if it already exists)

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    
    inv <- x$get.inv()
    if(!is.null(inv)){
        message("getting cached inverse...")
        return(inv)
    }
    
    data <- x$get.mat()
    inv <- solve(data,...)
    x$set.inv(inv)
    inv
}
